### ISSUE TITLE
PSP save videos can also be accessed from Filezilla

### ISSUE THREAD

**Issue by masterrite** [xy2iii/vita-handbook#1]
As the title says. I found this out the first time I roamed around filezilla. For psp games that saves playbacks into .avi videos, these videos cannot be accessed from vita's content manager. But with HENkaku, they can.

Connect to the vita via Filezilla, go to /ux0 -> pspemu -> VIDEO, and there they are.

Thought I should tell you guys and have it put into the vita hacking guide. This is an issue that could come in handy!

-billyliu1208, or, masterrite

**Comment by xy2i** [comment]
Added in[ dbecf5f](https://github.com/xy2iii/vita-handbook/commit/dbecf5f7b1f19ed05d149d57e45d7633a9b04e32).
If there are other cases which are dependant on /pspemu access, note them here as well.
